### ISSUE TITLE
建议升级到6后，示例文章相应的更改下说明

### ISSUE THREAD

**Issue by jamesliauw** [OrangeXC/udao#27]
1.建议按版本建分支，现在只有一个MASTER，不好进行版本管理
2.级到6后，示例文章相应的更改下说明，同时示例跑起来还有WARN，建议做一下LINT管理
谢谢,
PS,最近在research这个，向你学习

**Comment by OrangeXC** [comment]
@jamesliauw 
1.分支这个问题，不打算维护多个分支，只留 master，并且项目更新的速度非常快，出 7 还会立即更新到 7 的，持续学习直接定期拉最新项目就可以了
2.升级相关的文章随后会补上，6也是这两天刚升级的
3.还有你说的 lint 问题，项目一直都跑 lint，升级后没来得及处理，发现类似问题还希望你能直接提pr，毕竟我一个人精力有限
